[variables]
PRISMA_CLI_QUERY_ENGINE_TYPE = "binary"
PRISMA_CLIENT_ENGINE_TYPE = "binary"
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_22", "bun", "openssl"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run db:generate", "bun run build"]

[start]
cmd = "npx prisma db push --accept-data-loss && node .next/standalone/server.js"
