[variables]
PRISMA_CLI_QUERY_ENGINE_TYPE = "binary"
PRISMA_CLIENT_ENGINE_TYPE = "binary"
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_22", "bun", "openssl"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bunx prisma generate", "bun run build"]

[start]
cmd = "bunx prisma db push --accept-data-loss && bun .next/standalone/server.js"
