[build]
builder = "nixpacks"
buildCommand = "bun install && bunx prisma generate && bun run build"

[deploy]
startCommand = "bunx prisma migrate deploy && bun .next/standalone/server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/api"
healthcheckTimeout = 120

[[services]]
name = "easybeds"
