[build]
builder = "nixpacks"
buildCommand = "bun install && bunx prisma generate && bun run build"

[deploy]
startCommand = "npx prisma db push && node .next/standalone/server.js"
healthcheckPath = "/api"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
