[build]
builder = "nixpacks"
buildCommand = "npm install -g bun && bun install && ./node_modules/.bin/prisma generate && bun run build"

[deploy]

restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/api"
healthcheckTimeout = 60

[[services]]
name = "easybeds"
